project:
  type: book
  output-dir: docs

book:
  title: "Introduction to Bayesian Computing"
  author:
  - name: Dipali Vasudev Mestry 
    orcid: 0009-0003-3208-6638 
  - name: Amiya Ranjan Bhowmick 
    orcid: 0000-0002-7124-2213
  date: "2024-09-23"
  sidebar:
    style: docked
    background: light
  search: true
  downloads: [pdf, epub]
  sharing: [twitter, linkedin]
  date-format: long
  reader-mode: true
  page-footer:
    left: |
      Introduction to Bayesian Computing was written by Dipali Vasudev Mestry <a href="mailto:dipalimestry96@gmail.com">(dipalimestry96@gmail.com)</a>, and Amiya Ranjan Bhowmick <a href="mailto:amiyaiitb@gmail.com">(amiyaiitb@gmail.com)</a>/ <a href="mailto:ar.bhowmick@ictmumbai.edu.in">(ar.bhowmick@ictmumbai.edu.in)</a>..
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
      
  chapters:
    - index.qmd
    - intro.qmd
    - Illustrative Examples in practice.qmd
    - Bayesian Estimation for Linear Regression Problem.qmd
    - Bayesian Estimation to Nonlinear Regression Problem.qmd
    - Bayesian connection to Statistical Regularization.qmd
    - summary.qmd
    - references.qmd
bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
  pdf:
    documentclass: scrreprt
    includes:
      in-header:
        - |
          \usepackage{graphicx}
          \usepackage{ragged2e}
          \justifying
          \usepackage{imakeidx}
          \makeindex[intoc=true, columns=3, columnseprule=true, options=-s latex/indexstyles.ist]
    